---
# tasks file for demorole_01
- include_task: installjava.yaml
- include_task: createTomCatuser.yaml
- include_task: installTomcat.yaml
- include_task: permissions.yaml
- include_task: createservicefile.yaml
- include_task: starttomcat.yaml

